### ISSUE TITLE
Nested param included but not working when specifying the fields name

### ISSUE THREAD

**Issue by thenaazimkhan** [mattmilburn/strapi-plugin-menus#101]
# Environment
- node 16.19.0
- strapi: 4.9.0
- strapi-plugin-menus: 1.3.2

# What I have done
<img width="457" alt="image" src="https://user-images.githubusercontent.com/95960950/230852426-808484c2-c211-400e-8fb1-9cfee4adbddc.png">

<img width="472" alt="image" src="https://user-images.githubusercontent.com/95960950/230853130-39a0f203-95b3-4d73-9614-66771367f9ab.png">

The marketplace menu has 6 submenus but gets the children's data array empty.

# issue
not getting the menu in a nested format when specifying the fields means getting a flat list.

But if I pass the params without specifying fields then I got the correct JSON.

<img width="438" alt="image" src="https://user-images.githubusercontent.com/95960950/230853604-b113c39e-3277-431e-a609-33a63dda4d45.png">

<img width="582" alt="image" src="https://user-images.githubusercontent.com/95960950/230853704-631008c4-5d71-46ed-9116-b77c99f24656.png">

**Comment by mattmilburn** [comment]
Hi @thenaazimkhan I was able to reproduce the issue you discovered and I will try to make sure this is resolved in the next release, which should be later this week 👍🏻

**Comment by mattmilburn** [comment]
@thenaazimkhan Thank you again for raising this issue. It is now fixed in [the latest version 1.4.0](https://github.com/mattmilburn/strapi-plugin-menus/releases/tag/v1.4.0) of this plugin. Let me know how it goes for you 👍🏻

**Comment by thenaazimkhan** [comment]
Thanks, Mattmilburn


*Thanks & Regard*
*Naazim Khan*
*Software Engineer*
+971 50 381 2267
