### ISSUE TITLE
Feature request: Get menus by slug

### ISSUE THREAD

**Issue by Kaev** [mattmilburn/strapi-plugin-menus#103]
It would be great if we could get the menus by the unique slug that we set for our menus straight out of the box.
/menus/test-menu will probably be the same in all environments while menus/1 could be dev-test-menu or whatever menu was created first.

**Comment by mattmilburn** [comment]
Hi @Kaev This was actually a feature in the alpha version of the plugin but since then, the `Menu` and `MenuItem` schema types have been refactored to work the same as any other Strapi model, which makes them compatible with REST features.

Are you able to use `?filters[slug][$eq]=test-menu` with the [REST filters](https://docs.strapi.io/dev-docs/api/rest/filters-locale-publication#filtering) to achieve the same thing?

**Comment by thenaazimkhan** [comment]
Hi @mattmilburn I am doing the same way as you said.

**Comment by rihards-simanovics** [comment]
> Hi @Kaev This was actually a feature in the alpha version of the plugin but since then, the `Menu` and `MenuItem` schema types have been refactored to work the same as any other Strapi model, which makes them compatible with REST features.
> 
> Are you able to use `?filters[slug][$eq]=test-menu` with the [REST filters](https://docs.strapi.io/dev-docs/api/rest/filters-locale-publication#filtering) to achieve the same thing?

Hey Just found myself in the same situation here, for some reason it doesn't work. had only one menu up until this point so the filter worked but the moment I added another menu I quickly realised that filter doesn't work at all and just returns all menus.

I'm not a fan of hardcoding the IDs into the code and the only way to achieve what I need now is to do a double query to get the menus list with IDs and then filter them with slug.

**Comment by chaduhduh** [comment]
The suggested filters seem to work fine on my end. I am using params like @mattmilburn provided and plugin version `v1.5.0`

Examples:  
`/api/menus/?filters[slug][$eq]=main`
`/api/menus/?filters[slug][$eq]=secondary`

This also works to populate menu items:
`/api/menus/?nested=true&populate=*&filters[slug][$eq]=secondary`

**Comment by rihards-simanovics** [comment]
> The suggested filters seem to work fine on my end. I am using params like @mattmilburn provided and plugin version `v1.5.0`
> 
> Examples: `/api/menus/?filters[slug][$eq]=main` `/api/menus/?filters[slug][$eq]=secondary`
> 
> This also works to populate menu items: `/api/menus/?nested=true&populate=*&filters[slug][$eq]=secondary`

this issue is quite old so perhaps it was already patched; besides I'm using GraphQL now, but nice to know it's now fixed.
