### ISSUE TITLE
Absolute URL params containing "-" 

### ISSUE THREAD

**Issue by BennyMoser** [mattmilburn/strapi-plugin-menus#107]
Hi Matt,

i want to insert an absolute URL that has an additional param:
`/?lang=en-au`

This type of parameter is currently not allowed and I get the following error message: "This is an invalid URL format".
It would be really helpful if you could add the "-" to the allowed characters.

Tested on mac with v.1.4.0

**Comment by mattmilburn** [comment]
Hi @BennyMoser Thank you for raising this issue. This will be fixed in the next release. 👍🏻

**Comment by BennyMoser** [comment]
> @BennyMoser This is now fixed in the [latest version 1.4.1](https://github.com/mattmilburn/strapi-plugin-menus/releases/tag/v1.4.1) 🎉

Thank you for the quick fix 💪
