### ISSUE TITLE
why strapi-plugin-transformer plugin doesn't work

### ISSUE THREAD

**Issue by mingyuyuyu** [mattmilburn/strapi-plugin-menus#120]
![image](https://github.com/mattmilburn/strapi-plugin-menus/assets/32156701/a28e78d3-519a-4046-8694-fd49adc2fccd)
I read the docs ，it compatible with the Strapi Transformer plugin， but it doesn’t work when i use it  , any configs did i not config, help me, guys.
![image](https://github.com/mattmilburn/strapi-plugin-menus/assets/32156701/7b693bcd-e8c9-4a05-9f19-693fd68b7a7b)

"strapi-plugin-menus": "^1.4.3",
"strapi-plugin-transformer": "^3.1.0",
"@strapi/strapi": "4.11.1",

**Comment by mingyuyuyu** [comment]
response:
![image](https://github.com/mattmilburn/strapi-plugin-menus/assets/32156701/c303dd15-bf4c-41c6-b85b-573be233a4f8)

**Comment by mingyuyuyu** [comment]
@mattmilburn boss, can help see this issue, thanks

**Comment by francescob** [comment]
you need to specifically configure the transformer plugin like this
`  transformer: {
    enabled: true,
    config: {
      responseTransforms: {
        removeAttributesKey: true,
        removeDataKey: true,
      },
      plugins: {
        ids: {
          'menus': true,
        }
      }
    }
  },`

**Comment by mattmilburn** [comment]
Hi @mingyuyuyu It looks like @francescob is correct, version 3 of the transformer plugin requires you to specify which plugin UIDs should be transformed, which is most likely why it was not working for you. Earlier versions of the plugin did not require this.
