### ISSUE TITLE
Incompatible with Strapi v4.13.1

### ISSUE THREAD

**Issue by mattmilburn** [mattmilburn/strapi-plugin-menus#124]
In Strapi's latest version 4.13.1, an error occurs which _seems_ related to React v18.

Currently unsure what is specifically causing this.

<img width="1352" alt="Screenshot 2023-09-01 at 3 35 23 PM" src="https://github.com/mattmilburn/strapi-plugin-menus/assets/7082646/2b967726-34ce-43c0-9410-fa8c5e7c2a70">

**Comment by damian-balas** [comment]
@mattmilburn Hi, you need to update     
"react": "^17.0.2",
to 
"react": "^18.2.0",

in your package.json

I've added `yarn resolutions` with v18 and it started without this error.

**Comment by mattmilburn** [comment]
> @mattmilburn Hi, you need to update "react": "^17.0.2", to "react": "^18.2.0",
> 
> in your package.json
> 
> I've added `yarn resolutions` with v18 and it started without this error.

Hi @damian-balas I've been testing locally and it's true that using `"resolutions": { react: "^18.0.0" }` works as you described and it's a quick solution for now.

However, if I update the `react` dependency in the menus plugin then add it back into a Strapi app, it still gets this `react-dom/client` error. So far I've only been able to resolve it with the `resolutions` prop in my Strapi app `package.json` as you suggested and I'm still unable to implement a solution in the plugin itself. Oddly enough, this doesn't happen with any of my other plugins 🤷🏻‍♂️

**Comment by mattmilburn** [comment]
@damian-balas This issue is now fixed in the [latest v1.5.0](https://github.com/mattmilburn/strapi-plugin-menus/releases/tag/v1.5.0) of this plugin 👍🏻
