### ISSUE TITLE
Plugin missing from Strapi menu

### ISSUE THREAD

**Issue by tsvetlin** [mattmilburn/strapi-plugin-menus#13]
Hello!

After installing the plugin and creating the plugin.js file in strapi, the plugin is still missing from the menu.

What am I missing?

**Comment by tsvetlin** [comment]
M1 Mac has troubles installing some of the dependencies, running it throuh a Rosetta Terminal solved the issue.

**Comment by everythinginjs** [comment]
I have faced the same issue my OS is => Monterey 12.3.1 , mac book pro mvvk2
