### ISSUE TITLE
defaultAttrs do not change anything

### ISSUE THREAD

**Issue by maksymilianPadalak** [mattmilburn/strapi-plugin-menus#135]
Hi! Great plugin :) 

I know there is one thread opened about it already https://github.com/mattmilburn/strapi-plugin-menus/issues/37, but are defaultAttrs even needed? Removing them from strapi-server.js does not change the behavior of link layout. It would be great to have an option to use just customAttrs or to remove defaultAttrs since they are redundant and confusing (if I'm correct :D)

**Comment by mattmilburn** [comment]
Hi @maksymilianPadalak This will be possible in the future but for now, all menu items are required to use the built-in `title, url, target` fields. This future update will also allow customizing the `Menu` itself 👍🏻
