### ISSUE TITLE
Show menu endpoint in the documentation (OPENAPI spec gen) plugin

### ISSUE THREAD

**Issue by lunatiqqc** [mattmilburn/strapi-plugin-menus#137]
Hi, is it possible have the api endpoint (api/menus) shown in the generated openAPI spec generated with the Documentation plugin?

**Comment by mattmilburn** [comment]
Hi @lunatiqqc Thank you for raising this issue. I have not checked the compatibility with the documentation plugin in a while so I'll have to revisit that soon 👍🏻

**Comment by mattmilburn** [comment]
Hi @lunatiqqc Documentation plugin is now supported in the [latest v1.6.0 release](https://github.com/mattmilburn/strapi-plugin-menus/releases/tag/v1.6.0) of this plugin 🎉
