### ISSUE TITLE
Import & Export feature

### ISSUE THREAD

**Issue by TurtleTower** [mattmilburn/strapi-plugin-menus#16]
To import & export menu items would be great

**Comment by mattmilburn** [comment]
Just curious, are you working with a situation where you would have **a lot** of menus to work with? Currently the plugin assumes you won't be making hundreds (or even close to 100) menus to appear on a website or app 🤷🏻

**Comment by daan-ef2** [comment]
+1, also nice if it could be used with the config-sync plugin, or a how to how you can implement it in the config-sync module.

**Comment by mattmilburn** [comment]
@TurtleTower This plugin has updated recently with lots of breaking changes. Currently, there are no plans to give this plugin specific import/export feature. But in the latest version 1.0.0 the data format in the REST response is now consistent with other data models in Strapi. If needing to import/export then that should be handled in a separate plugin that focuses on importing and exporting data in Strapi. I'm not sure if one exists yet but the alternative would be to use Strapi's database migration options.
