### ISSUE TITLE
Make Menu Available via Slug

### ISSUE THREAD

**Issue by derschiw** [mattmilburn/strapi-plugin-menus#163]
Hey there 😊 

I very much like your plugin for its simplicity. I just wondered wether it would be a possible to make the menus available via its slug. For now it is only possible to search it via id, like so:
```js
const mainMenu = await fetch(`${API_BASE_URL}/api/menus/1?`);
const footerMenu = await fetch(`${API_BASE_URL}/api/menus/2`);
```

In this case it would be nice to be able to search it this way (as the menu already has a `slug` attribute):
```js
const mainMenu = await fetch(`${API_BASE_URL}/api/menus/main`);
const footerMenu = await fetch(`${API_BASE_URL}/api/menus/footer`);
```

Not 100% necessary but would be nice to have. Thanks and bye!

**Comment by ayhid** [comment]
You can use `filters` for this

**Comment by chaduhduh** [comment]
Here is an example: ```/api/menus/?filters[slug][$eq]=main```

**Comment by rihards-simanovics** [comment]
> You can use `filters` for this

just stumbled across this, nice! This does indeed work now! I recall this was an issue years ago but seems to be a feature now. thanks!

@derschiw try this: `/api/menus?filters[slug][$eq]=main&nested=true&populate=%2A`

**Comment by derschiw** [comment]
Ok thanks for your reply! :)
