### ISSUE TITLE
Menu Missing in Strapi Admin

### ISSUE THREAD

**Issue by jared-leddy** [mattmilburn/strapi-plugin-menus#19]
### Problem

- In the files section for ``./src/extensions/`` there is not a folder created for menu or menus. 
- In the Strapi Admin area, there is not a left-hand sidebar menu item for "menus". 
- Node v16.14.0

### Installation

Installed the plugin per the docs. 

```
npm install strapi-plugin-menus
```

Package.json file now shows the plugin was installed.

```json
  "dependencies": {
    "@strapi/strapi": "4.1.7",
    "strapi-plugin-menus": "^0.2.4"
  },
  "engines": {
    "node": ">=16.x.x",
    "npm": ">=6.0.0"
  },
```

### Config Setup

The [docs on Strapi](https://market.strapi.io/plugins/strapi-plugin-menus#install-now-section) don't explicitly state to "create a config file", but I've tested with and without the example provided. The same results happen either way.

File: ./config/plugins.js
Code:
```js
module.exports = {
  'menus': {
    enabled: true,
    config: {
      maxDepth: 3,
    },
  },
};
```

### Strapi Plugins Menu

In the Strapi admin menu, when you click on "plugins", Menu is present.

**Comment by everythinginjs** [comment]
+1

**Comment by everythinginjs** [comment]
yarn build
yarn develop

fixed my issue.

**Comment by jared-leddy** [comment]
@mattmilburn, yes. I used the npm versions. I had another ticket open, and this was the same solution that fixed both of them.
