### ISSUE TITLE
Extending with new field not showing in the Menu Item layout

### ISSUE THREAD

**Issue by bogh** [mattmilburn/strapi-plugin-menus#21]
### Problem

Trying to extend the menu to add a new attribute, but doesn't show in the layout.

I followed the `Extending` tutorial and the field is created in db but doesn't show in the layout at allow. The config is loaded correctly from the backend to admin panel front.

### Versions:

- "@strapi/strapi": "4.1.7",
- "strapi-plugin-menus": "^0.2.4"
- "node": v16.13.2

**Comment by OnekO** [comment]
I've the same problem creating a relation type field, looks like it can't found the necessary metadata.

**Comment by rttmax** [comment]
+1

**Comment by Flowko** [comment]
@mattmilburn first i would like to thank you for creating this helpfull plugin, im facing the same issue with the latest version from both strapi and ur plugin:

### Versions:
"@strapi/strapi": "4.1.10",
"strapi-plugin-menus": "^0.3.1"
"node": v16.14.2

### Problem:

Extend MenuItem schema attributes, kinda
my plugin file:
i did run a build but with no luck!
```js
menus: {
    enabled: true,
    config: {
      layouts: {
        menuItem: {
          link: [
            {
              input: {
                label: "Shortname",
                name: "shortname",
                type: "text",
                description:
                  "Provide a shortname for the menu item. This will be used to for translation.",
              },
              grid: { col: 6 },
            },
          ],
        },
      },
    },
  },
```

this does change the UI tho, but not the schema it self,
![image](https://user-images.githubusercontent.com/35883748/168183199-2ca9e67e-1338-4faf-a5ae-d5928e11e3d3.png)

if i go and add a shortname and hit save, it just saves fine and refreshs, and shortname gets lost.

checking the data that gets returned from the `menus` api call. u can see there's no shortname, so its probably something wrong with adding the new extended fields to the db somehow
![image](https://user-images.githubusercontent.com/35883748/168183333-e491a49c-6d3b-4cac-b5e7-178ee26463b1.png)

**Comment by mattmilburn** [comment]
@Flowko Did you remember to extend the `MenuItem` schema in addition to the form layouts config as described at this link https://github.com/mattmilburn/strapi-plugin-menus#1-extend-menuitem-schema-attributes?

**Comment by mattmilburn** [comment]
> I've the same problem creating a relation type field, looks like it can't found the necessary metadata.

Hi @OnekO Can you provide your config for this relation field? And are you remembering to extend the `MenuItem` schema as well as the form layout?

**Comment by Flowko** [comment]
> @Flowko Did you remember to extend the `MenuItem` schema in addition to the form layouts config as described at this link https://github.com/mattmilburn/strapi-plugin-menus#1-extend-menuitem-schema-attributes?

damn, tottaly missed that, thanks
