### ISSUE TITLE
ordering top level menus

### ISSUE THREAD

**Issue by everythinginjs** [mattmilburn/strapi-plugin-menus#28]
Hello there, I think there is no way to order the items in top level menus. would be appreciated to give me a hint.

**Comment by mattmilburn** [comment]
I have not experienced this issue before. Can you provide more details or screenshots?

This plugin has also released to a new major version today. I would recommend upgrading to that version of the plugin first to see if it resolves any issues.

**Comment by everythinginjs** [comment]
@mattmilburn , that was a misunderstanding and a little bit bad user experience , I made my menus right inside the menus
I mean here:
<img width="781" alt="Screen Shot 2022-07-30 at 1 07 07 PM" src="https://user-images.githubusercontent.com/34276557/181902678-51bb6d9a-3862-4091-acb6-8c33b4254498.png">
and therefor, I could not drag and drop them, it took me 20 mins 😂  to understand top once are my menus BRAIN FART.
thanks for the reply. I close this since it's not a real issue.
