### ISSUE TITLE
Localization (i18n) supported?

### ISSUE THREAD

**Issue by mmathys** [mattmilburn/strapi-plugin-menus#29]
Hi, this plugin looks great. I'm developing a site which is available in two languages, is there any support for localization available?

Thanks!

**Comment by mmathys** [comment]
For anyone in the future looking for this – [the navigation plugin](https://market.strapi.io/plugins/strapi-plugin-navigation#install-now-section) supports localization as of 2.1.0-beta.1.

**Comment by mattmilburn** [comment]
Hi @mmathys Extra support for locales are on the way. There have been a number of higher priority items that finally released today in a new major version of the plugin and locale support is on the roadmap. 👍🏻
