### ISSUE TITLE
Relation Items not loading

### ISSUE THREAD

**Issue by Maxdola** [mattmilburn/strapi-plugin-menus#31]
I am trying to add a Relation in the Menu, but the relation items arent loading.

This request keeps failing: 

`
POST /admin/plugins/menus/edit/menus/relations/page_otm?limit=20&start=0 (0 ms) 405
`

strapi-server.js:
```
'use strict';

module.exports = plugin => {
  // Get current `MenuItem` attributes.
  const defaultAttrs = plugin.contentTypes[ 'menu-item' ].schema.attributes;

  // Define custom attributes for `MenuItem` the same way they would be defined
  // on any other schema.
  const customAttrs = {
    page_otm: {
      type: 'relation',
      relation: 'manyToOne',
      target: 'api::page.page',
    },
  };

  // Extend the `MenuItem` content type with custom attributes.
  plugin.contentTypes[ 'menu-item' ].schema.attributes = {
    ...defaultAttrs,
    ...customAttrs,
  };

  return plugin;
};
```

plugins.js:
```
menus: {
    config: {
      maxDepth: 2,
      layouts: {
        menuItem: { 
          link: [
            {
              input: {
                label: 'Linked Page',
                name: 'page_otm',
                type: 'relation',
              },
              grid: {
                col: 6,
              },
            },
          ],
        },
      },
    },
  },

```
strapi version: 4.1.11
menus version: 0.3.2

**Comment by rubyjasmin** [comment]
👍

**Comment by BenjaminSchulte** [comment]
I actually had the same problem with strapi 4.2.0.

I could solve the problem by setting the environment variable `STRAPI_ADMIN_BACKEND_URL` to my full `https://server-backend.url` **before** I call `strapi build`.

Background: The `admin/src/utils/axios-instance.js` file instanciates an axios class with the base URL given by `STRAPI_ADMIN_BACKEND_URL`. If the environment variable is empty, axios seems to use the current URL as relative URL(?). When using `strapi build` the environment variable is copied into the source code, so you have to set it before building the admin UI javascript.

Maybe it'd help to add this hint to the **Troubleshooting** part of the README.md?

**Comment by mattmilburn** [comment]
Hi @Maxdola Sorry for the late response! I have released a new, major update for this plugin today which may help resolve your issues. Previously, the plugin did not feature complete support for Strapi's REST params, but the latest version does 🙂

**Comment by Maxdola** [comment]
> Hi @Maxdola Sorry for the late response! I have released a new, major update for this plugin today which may help resolve your issues. Previously, the plugin did not feature complete support for Strapi's REST params, but the latest version does 🙂

Thank you very much! I will try it tomorrow.
