### ISSUE TITLE
Tree item dark mode visibility problem

### ISSUE THREAD

**Issue by mehrad-meraji** [mattmilburn/strapi-plugin-menus#35]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `strapi-plugin-menus@0.3.2` for the project I'm working on.

The menu items weren't clearly visible in "Dark Mode"

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/strapi-plugin-menus/admin/src/components/TreeMenuItem/styled.js b/node_modules/strapi-plugin-menus/admin/src/components/TreeMenuItem/styled.js
index 8ff5674..9931143 100644
--- a/node_modules/strapi-plugin-menus/admin/src/components/TreeMenuItem/styled.js
+++ b/node_modules/strapi-plugin-menus/admin/src/components/TreeMenuItem/styled.js
@@ -16,6 +16,7 @@ export const Wrapper = styled( Box )`
   cursor: pointer;
   position: relative;
   z-index: 2;
+  color: ${({ theme }) => theme.colors.neutral800};
 
   ${({ theme, hasErrors, isActive }) => {
     if ( isActive ) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by mattmilburn** [comment]
Hi @mehrad-meraji Thanks for submitting this issue! 👍🏻  I have included your dark mode suggestion into the latest v1.0.1 of this plugin.
