### ISSUE TITLE
[Question] Integrate plugins into tables that already exist

### ISSUE THREAD

**Issue by ryuhangyeong** [mattmilburn/strapi-plugin-menus#39]
## Etc

thank you for making such a great plugin!

## Question

1. For example, assuming you have an already configured strapi table, can you connect it to your plugin and use it?

From what I've looked at it seems impossible, but I'm not sure, so I'm leaving an issue.

Is my question the same as #37?

**Comment by mattmilburn** [comment]
Hi @ryuhangyeong Can you be more specific in what you're trying to accomplish?

Adding a relation field to a `MenuItem` is certainly possible. However, having that relation auto-fill the `slug` value somehow is not currently supported but is definitely going to be supported in a future release.

**Comment by ryuhangyeong** [comment]
1. I already have table data in use and I was wondering if it would be possible to integrate this into your plugin.

For example, I have table information about a to-do list, and I was wondering if it is possible to change the order, add, or delete by linking this to a plugin!

**Comment by mattmilburn** [comment]
@ryuhangyeong Okay, I think I understand what you mean. But one more time for my own clarity... we're talking about having custom content types, such as a `Todo` and `TodoItem` that would replace the `Menu` and `MenuItem` that come with the plugin. Then the plugin would connect with those content types and display their fields in the menus plugin UI, thus serving as an alternative content manager for the `Todo` and `TodoItems`?

If that's not what you're talking about, it's still greatly intrigued by what I just described 😄

**Comment by ryuhangyeong** [comment]
@mattmilburn

yes that's correct!

Let me summarize my requirements

1. The user-defined table already exists.

![스크린샷 2022-08-03 오후 2 35 22](https://user-images.githubusercontent.com/27342882/182531632-fe8adf29-4ff8-4428-9970-5f2c95a62550.png)

2. i can change the order of categories and add or edit categories.

![스크린샷 2022-08-03 오후 2 37 06](https://user-images.githubusercontent.com/27342882/182531951-56d938e3-9f39-4510-a133-1ab33b4866a2.png)

This is probably a feature many people want!
