### ISSUE TITLE
Question: Whether to save the database

### ISSUE THREAD

**Issue by ryuhangyeong** [mattmilburn/strapi-plugin-menus#41]
## Question

I have more questions! I have used strapi with mysql before and I would like to use your plugin.

Does adding a menu add data to mysql? Or is it not? (is it only stored in local sqlite?) thanks

**Comment by mattmilburn** [comment]
@ryuhangyeong Yes, adding a menu will add data into whatever database you are using, whether it be mysql, postgres, sqlite, etc. The plugin was designed to function the same way other data works in Strapi.

**Comment by ryuhangyeong** [comment]
@mattmilburn thank you!
