### ISSUE TITLE
Is it possible to store different properties for each depth?

### ISSUE THREAD

**Issue by ryuhangyeong** [mattmilburn/strapi-plugin-menus#42]
## Question

- gnb 1
  - gnb 1-1
    - gnb 1-1-1

1, 1-1, 1-1-1 exist. (up to 3)

Is it possible to customize the attributes that can be entered for each depth?

## Example

- gnb 1
  - name
  - target

- gnb 1-1
  - sub name
  - etc...

- gnb 1-1-1
  - badge

**Comment by mattmilburn** [comment]
@ryuhangyeong Sorry, it is not a supported feature with this plugin right now. I'll keep it in mind for the future though.

**Comment by mattmilburn** [comment]
@ryuhangyeong Sorry, it is not a supported feature with this plugin right now. I'll keep it in mind for the future though.
