### ISSUE TITLE
Custom Attributes not being saved

### ISSUE THREAD

**Issue by tefkah** [mattmilburn/strapi-plugin-menus#48]
Hi! Great plugin, but I'm having trouble setting new attributes for the menus.
The form appears, but whenever I edit non-default values they do not get saved for some reason. Any idea what causes this?

I feel like the `extensions/strapi-server.js` is not being picked up, as the `console.log` i put in there also never appears anywhere in my logs.

This is after clearing the cache and dist folder multiple times, so I don't think it's that.

### Config
```ts
export default {
  enabled: true,
  config: {
    maxDepth: 3,
    layouts: {
      menuItem: {
        link: [
          {
            input: {
              label: 'Icon',
              name: 'icon',
              type: 'media',
            },
          },
          {
            input: {
              label: 'Description',
              name: 'description',
              type: 'text',
              maxLength: 100,
            },
          },
        ],
      },
    },
  },
}
```

### ./src/extensions/menus/strapi-server.js
```ts
'use strict'

module.exports = (plugin) => {
  // Get current `MenuItem` attributes.
  const defaultAttrs = plugin.contentTypes['menu-item'].schema.attributes

  // Define custom attributes for `MenuItem` the same way they would be defined
  // on any other schema.
  const customAttrs = {
    description: {
      type: 'text',
    },
    icon: {
      type: 'media',
      allowedTypes: ['images'],
      multiple: false,
    },
  }

  // Extend the `MenuItem` content type with custom attributes.
  plugin.contentTypes['menu-item'].schema.attributes = {
    ...defaultAttrs,
    ...customAttrs,
  }
  console.log(plugin)

  return plugin
}
```

### Clip
https://user-images.githubusercontent.com/21983833/185692492-f96a97fb-18d5-4ac2-88b3-7f3853ed1587.mov

**Comment by tefkah** [comment]
Ah nvm

I'm using TS with strapi and my `tsconfig.json` does not pick up `.js` files. Changing the extension to `.ts` solved the issue, although I could probably also change my `tsconfig.json`

**Comment by mattmilburn** [comment]
Hi @tefkah Thanks for pointing this out. I may still update the README to mention using either `js` or `ts` depending on your setup 👍
