### ISSUE TITLE
Menu items are not returned in api request

### ISSUE THREAD

**Issue by Bodokh** [mattmilburn/strapi-plugin-menus#54]
In the admin UI the menus show up correctly with the correct menu items/children. 
The public access to the menus api requests are open.

When I send a request I get something along the lines of:
<img width="488" alt="Screen Shot 2022-09-22 at 10 46 32" src="https://user-images.githubusercontent.com/8866248/191688700-8c8ee99e-3667-4417-b561-b5bb31801a8c.png">

As can be seen there are no menu items in the response. No matter what I try to request I can only get the menu itself without the menu items.

This might be due to upgrading Strapi from 4.1 to 4.3. 
Any clue why something like could happen?

**Comment by Bodokh** [comment]
> Hi, please try to add `?populate=*` to your URL as described in the section "**Example with population**" of https://github.com/mattmilburn/strapi-plugin-menus#api-usage

Of course I tried that as well, also tried using populate with the field names.
I entered the node_module into the menu.js controller and added a log right after the findOne command and no menu items inside.

**Comment by Bodokh** [comment]
OK, Found the issue, feeling kind of silly, but the public permissions were only for the menu findOne and not the menu items.
Though before updating I am pretty sure I did not need public permissions for the menu items for the menu method to show me the menu items.

**Comment by mattmilburn** [comment]
Hi @Bodokh Glad you were able to resolve your issue!

The earlier versions of the menus plugin was too opinionated and lacked certain customizations. So when v1.0.0 was released, it represented a major refactoring and much of the config for `Menu` and `MenuItem` schemas were put back into the hands of the developer. This provides a lot more freedom for the developer and in turn, a little bit more responsibility. 🙂

**Comment by uni-vinay-p** [comment]
@mattmilburn  Is there any way I can get a submenu item via API?
