### ISSUE TITLE
[issue] Nested items population with relations (media)

### ISSUE THREAD

**Issue by aurelienbobenrieth** [mattmilburn/strapi-plugin-menus#66]
Hello (again²),

Issue related to: #56 (but not solved for me).

I have added a custom media field called `card_image` inside my item.

It seems I cannot request the populated media field combined with the nested parameter.

**Case 1:**
`GET` `/api/menus/1?nested&populate=*`

Populates my nested items but without my media relation...

**Case 2:**
`GET` `/api/menus/1?populate[items][populate][0]=card_image`

Populates my menu with the required fields (and my media relation) but flattened...

**Case 3:**
`GET` `/api/menus/1?nested&populate[items][populate][0]=card_image`

Like case 2, the `nested` parameter is completly ignored.

Is this a bug, an error from me in my implementation, or just something that is not yet possible ?

**Comment by aurelienbobenrieth** [comment]
[SOLVED]

Okay so actually the package works fine, but there is a lack of information regarding this point in the documentation imho.

The actual way to populate nested relations as well as keeping the nesting is to specify the `parent` property inside the query parameters.

❌
`GET` `/api/menus/1?nested&populate[items][populate][0]=card_image`
Populates `card_image` relation without nesting.

✅ 
`GET` `/api/menus/1?nested&populate[items][populate][0]=parent,card_image`
Populates `card_image` relation with nesting kept.

**Comment by simosalsi** [comment]
Found this while looking to fix this bug.

I would suggest reopening this issue under "Documentation" or something similar as it would be of GREAT value to have this info be easier to find.

Thank you for the great plugin btw!
