### ISSUE TITLE
[issue] Item attributes display

### ISSUE THREAD

**Issue by aurelienbobenrieth** [mattmilburn/strapi-plugin-menus#67]
Hello (again),

Small issue:
Inside the admin, when you have a loooong menu with multiple items, if you create a new nested item without having clicked on another item before, the attributes panel will not display until you scroll a bit.

I guess that the panel being sticky with the scroll should have another event listener such as `item:created` to trigger the sticky behavior to cope with this issue.

**Comment by mattmilburn** [comment]
Hi @aurelienbobenrieth Thanks for raising the issue for this bug. I will make sure it is fixed in the next release 👍🏻

**Comment by mattmilburn** [comment]
@aurelienbobenrieth This is now fixed in the latest [version 1.2.0](https://github.com/mattmilburn/strapi-plugin-menus/releases/tag/v1.2.0) of the plugin. Thanks again for raising this issue 🎉
