### ISSUE TITLE
Strapi v4.5.2

### ISSUE THREAD

**Issue by muhammed-demir** [mattmilburn/strapi-plugin-menus#68]
The menu plugin for **Strapi v4.5.2** does not work. When you click Create Menu Item, a blank page is displayed.

For Strapi **v4.5.1** is working fine.

**Comment by graphicfox** [comment]
Same here. Also already created menus cant be opened. 

It seams that there are problems with the build? 

``Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at $n (main.82ecf42c.js:10534:14898)
    at main.82ecf42c.js:10530:51161
    at qo (main.82ecf42c.js:10530:63146)
    at Vu (main.82ecf42c.js:10534:11017)
    at dd (main.82ecf42c.js:10534:992)
    at Sd (main.82ecf42c.js:10534:920)
    at $s (main.82ecf42c.js:10534:771)
    at bc (main.82ecf42c.js:10532:11158)
    at main.82ecf42c.js:10530:39637
    at i.unstable_runWithPriority (main.82ecf42c.js:10600:3941)``

**Comment by genikineg** [comment]
Same here.

strapi version
v4.5.2

node version
v14.21.1

**Comment by panjosef** [comment]
Hey @muhammed-demir , @genikineg , @graphicfox , @Shreyas19971999 , @thomasbrunstrom ,

new version will fix the problem with Menus!

strapi version
v4.5.3

**Comment by mattmilburn** [comment]
Hey everyone @muhammed-demir @graphicfox @genikineg @Shreyas19971999 @panjosef 

The menus plugin has now [released version 1.2.0](https://github.com/mattmilburn/strapi-plugin-menus/releases/tag/v1.2.0) with compatibility for Strapi v4.5x 🎉 

Please let me know if you are still having issues with the plugin after upgrading to its latest version.
