### ISSUE TITLE
Node 18.12.1 LTS support

### ISSUE THREAD

**Issue by negativespacestudios** [mattmilburn/strapi-plugin-menus#69]
Hi,

Firstly I'd like to say a huge thankyou for developing the menu's plugin for Strapi. It's really useful and much appreciated.

Recently we just released our current site build to a staging server that had the latest LTS version of node installed (18.12.1). During the build pipeline the build failed due to the menus plugin stating that the node version needs to be between 12.x.x and 16.x.x

It would be fantastic if you could add support for the latest LTS node version. We ended up downgrading the version that is installed on the server to 16 to allow Strapi & the menus plugin to run properly.

```
# package.json
"engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
```

**Comment by mattmilburn** [comment]
@negativespacestudios This is now updated in the latest [version 1.2.0](https://github.com/mattmilburn/strapi-plugin-menus/releases/tag/v1.2.0) of the plugin. Thanks again for raising this issue 🎉

**Comment by negativespacestudios** [comment]
Thanks @mattmilburn, that's magic!

**Comment by antokhio** [comment]
Hi, this probably should be graceful reopen since now it's 20 that is lts, i can suggest just remove `<=` from package
