### ISSUE TITLE
How to store custom attributes to populate them in endpoint?

### ISSUE THREAD

**Issue by AF20181** [mattmilburn/strapi-plugin-menus#73]
Hi there, I have set up all of the Extend section like form layout extension as well as the schema extension but unfortunately the enpoint (api/menus/?populate=*) dosnt show my custom attributes as they are not stored if I save my menu in the backend. What do I miss here?

StrapiV 4.5.3
strapi-plugin-menus@latest

**Comment by mattmilburn** [comment]
Hi @AF20181 Can you provide more details on your `package.json` and plugins config?

Are you working with custom **relation** attributes that are missing in the content API?

**Comment by AF20181** [comment]
I couldn't see the forest for the trees and had wrongly named strapi-server.js. Thx for your awesome work!
