### ISSUE TITLE
Item of schema type 'media' are not returning through api

### ISSUE THREAD

**Issue by johncorlett-ultracommerce** [mattmilburn/strapi-plugin-menus#76]
_./src/extensions/menus/strapi-server.js_ contains schema:

 const customAttrs = {
      menuItemIcon: {
        type: 'media',
        allowedTypes: [ 'images' ],
        multiple: false,
      },
      menuItemThumbnail: {
        type: 'media',
        allowedTypes: [ 'images' ],
        multiple: false,
      },
      menuItemFeatureImage: {
        type: 'media',
        allowedTypes: [ 'images' ],
        multiple: false,
      },
    };

_http://localhost:1337/api/menus/3?populate=*_   returns:

 "items": [
            {
                "id": 17,
                "order": 0,
                "title": "Profiles",
                "url": "/products",
                "target": null,
                "createdAt": "2022-12-28T22:01:41.002Z",
                "updatedAt": "2022-12-29T22:42:09.712Z"
            },

Changing type to string allows the custom item to appear in the api as a null.

**Comment by mortenwibrand** [comment]
I had the same problem. Solved it by using this plugin: https://github.com/Barelydead/strapi-plugin-populate-deep

In my case with a menu in three levels, I used `/menus/1?nested=true&populate=deep,3`
