### ISSUE TITLE
Unable to visualize relation fields

### ISSUE THREAD

**Issue by jowavp** [mattmilburn/strapi-plugin-menus#84]
Hi,

I created some custom fields on the menu item.

./src/extensions/menus/strapi-server.js

`module.exports = plugin => {
    // Get current `MenuItem` attributes.
    const defaultAttrs = plugin.contentTypes['menu-item'].schema.attributes;

    // Define custom attributes for `MenuItem` the same way they would be defined
    // on any other schema.
    const customAttrs = {
        description: {
            type: 'text',
        },
        icon: {
            type: 'string'
        },
        application: {
            type: 'relation',
            relation: 'oneToOne',
            target: 'api::application.application',
        },
        scopes: {
            type: 'relation',
            relation: 'oneToMany',
            target: 'api::scope.scope',
        },
    };

    // Extend the `MenuItem` content type with custom attributes.
    plugin.contentTypes['menu-item'].schema.attributes = {
        ...defaultAttrs,
        ...customAttrs,
    };

    return plugin;
};`

To visualize these new fields for the content manager.
I added a file ./config/plugin.ts

```
export default {
    menus: {
        config: {
            layouts: {
                menuItem: { // This is the menu item edit panel.
                    relations: [
                        {
                            input: {
                                label: 'Application',
                                name: 'application',
                                type: 'relation',
                            },
                        },
                        {
                            input: {
                                label: 'Scopes',
                                name: 'scopes',
                                type: 'relation',
                            },
                        },
                    ],
                    link: [ 
                        {
                            input: {
                                label: 'Icon',
                                name: 'icon',
                                type: 'string',
                                placeholder: 'Iconname'
                            },
                            grid: {
                                col: 12,
                            },
                        }, {
                            input: {
                                label: 'Description',
                                name: 'description',
                                type: 'textarea',
                                description: 'Description of the menu item',
                                placeholder: 'Type something...'
                            },
                            grid: {
                                col: 12,
                            },
                        },
                    ],
                },
            },
        },
    },
}
```

In strapi, I see the new custom fields icon and description, but the relations are not appearing.
I tried to put them in the same tab, but that didn't solve the problem.

I'm using strapi 4.6.0
and menu plugin 1.2.2

![image](https://user-images.githubusercontent.com/4183804/215482419-2f2cb3cf-5173-4f02-914e-50bf1d8394a6.png)

![image](https://user-images.githubusercontent.com/4183804/215482760-88af604a-41f8-4b2f-81fe-c37d14c71253.png)

kr,
Jowa

**Comment by mattmilburn** [comment]
Hi @jowavp thanks for raising this issue. Strapi v4.6.0 has introduced something that is breaking relations in this plugin. A fix for this plugin is currently in progress 👍🏻

**Comment by mattmilburn** [comment]
@jowavp This plugin has new updated to version 1.3.0 which brings support for Strapi v4.6x. Please let me know if this solves your issue.

**Comment by Tiffoun** [comment]
Hi @mattmilburn I am on strapi 4.6.0 and the relations does still does not appears.

**Comment by Tiffoun** [comment]
And the integers appears as not supported.

**Comment by mattmilburn** [comment]
Hi @Tiffoun I'm unable to find any issues in v4.6. Can you provide more info on your plugin config and extension?

**Comment by Tiffoun** [comment]
Hi @mattmilburn,
strapi version : 4.6.0
menus version : 1.3.1
file strapi-server.js : 
![image](https://user-images.githubusercontent.com/99135733/219414190-8cb92b25-8026-461f-bebc-fd45b4b19bf5.png)
and the plugins.ts :
![image](https://user-images.githubusercontent.com/99135733/219414450-a93f8227-d6db-4b3a-b23c-fb949b259fca.png)

the menu screen :
![image](https://user-images.githubusercontent.com/99135733/219415028-2cd6fd62-59f8-46b7-9c29-3b7370c4c6c8.png)
the pb with the integers was my mistake but now it seems that the float is not saved / displayed correctly.
When I call the strapi API it returns :
![image](https://user-images.githubusercontent.com/99135733/219416619-5d9110a8-eb86-4d99-838e-1bd5d0b9f40f.png)

**Comment by Tiffoun** [comment]
@mattmilburn the problem was that the strapi-server file was in js instead of ts.
Thanks for you time.

**Comment by mattmilburn** [comment]
@Tiffoun Great! Glad you were able to resolve your issue 🙂
