### ISSUE TITLE
does it work with GraphQL?

### ISSUE THREAD

**Issue by violabg** [mattmilburn/strapi-plugin-menus#9]
cool plugin, does it work with GraphQL?

**Comment by mattmilburn** [comment]
I have not yet included specific support for GraphQL. I just did not have time to bake in every feature right away. Happy to review a pull request though. 🙂 

Otherwise, I'll add GraphQL support to the roadmap 👍🏻

**Comment by everythinginjs** [comment]
hey @mattmilburn thanks for handy plugin, haven’t you set up GraphQL support yet? I am on working on a Gatsby-Strapi project with a tight schedule. would be appreciated if I know estimated time of completion.

**Comment by everythinginjs** [comment]
@mattmilburn  I just made a quick [gatsby source api  for menus](https://gist.github.com/everythinginjs/ea902207b0038c5d671d17880f37ef6d
) but not complete just something that I can work with.
I can later develop that further.
