### ISSUE TITLE
How to add menu as relation?

### ISSUE THREAD

**Issue by jmohan-1minus1** [mattmilburn/strapi-plugin-menus#90]
How can I add a menu as a relation to a single/collection type or component?

Sorry, not a bug or issue. I just can't work this out. I just want to be able to select one of my menus as a relation. So for example, a Page or Footer could have a specific menu related to it.

Great plugin btw!

![393235bd-4241-4aa9-ac11-3d0da2c1dbc9](https://user-images.githubusercontent.com/110416271/219795725-aa7efd0f-da40-4703-82fe-a63d2a8b6205.png)

**Comment by Tiffoun** [comment]
I didn't find a way to do it by the Content builder but you can add something like : 
```
"my-menu": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "plugin::menus.menu-item",
      "inversedBy": "menu_global_relation"
    }
```
in src/api/global/content-types/global/schema.json in the 'attributes' section

**Comment by jmohan-1minus1** [comment]
Brilliant! Thanks for that
